import React from "react";
import {
  FaJsSquare,
  FaPython,
  FaNodeJs,
  FaReact,
  FaHtml5,
  FaCss3Alt,
  FaCode,
} from "react-icons/fa";
import {
  SiTypescript,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiPhp,
  SiLaravel,
  SiGo,
  SiRust,
  SiCplusplus,
  SiDart,
  SiFlutter,
  SiAstro,
  SiKotlin,
  SiSwift,
  SiSharp,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSvelte,
  SiNuxtdotjs,
  SiExpress,
  SiNestjs,
  SiSpring,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiFirebase,
  SiSupabase,
  SiPrisma,
  SiDocker,
  SiKubernetes,
  SiGraphql,
  SiRedis,
  SiSocketdotio,
  SiTailwindcss,
  SiSass,
  SiBootstrap,
  SiMui,
  SiChakraui,
  SiStyledcomponents,
  SiElectron,
  SiReact,
  SiUnity,
  SiUnrealengine,
  SiBlender,
  SiWebpack,
  SiVite,
  SiEslint,
  SiPrettier,
  SiJest,
  SiCypress,
  SiStorybook,
  SiFigma,
  SiAdobe,
  SiLinux,
  SiMacos,
  SiVim,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiDigitalocean,
  SiAmazons3,
  SiAmazon,
  SiGooglecloud,
  SiTensorflow,
  SiPytorch,
  SiOpencv,
  SiNumpy,
  SiPandas,
  SiScipy,
  SiJupyter,
  SiAnaconda,
  SiR,
  SiSolidity,
  SiWeb3Dotjs,
  SiEthereum
} from "react-icons/si";

export const getLanguageIcon = (language: string) => {
  const iconMap: { [key: string]: React.ReactElement } = {
    'JavaScript': <FaJsSquare className="w-5 h-5 text-yellow-400" />,
    'TypeScript': <SiTypescript className="w-5 h-5 text-blue-400" />,
    'React': <FaReact className="w-5 h-5 text-cyan-400" />,
    'Next.js': <SiNextdotjs className="w-5 h-5 text-white" />,
    'Node.js': <FaNodeJs className="w-5 h-5 text-green-400" />,
    'Python': <FaPython className="w-5 h-5 text-yellow-300" />,
    'HTML': <FaHtml5 className="w-5 h-5 text-orange-400" />,
    'CSS': <FaCss3Alt className="w-5 h-5 text-blue-400" />,
    'Vue': <SiVuedotjs className="w-5 h-5 text-green-400" />,
    'Angular': <SiAngular className="w-5 h-5 text-red-400" />,
    'PHP': <SiPhp className="w-5 h-5 text-purple-400" />,
    'Laravel': <SiLaravel className="w-5 h-5 text-red-400" />,
    'Go': <SiGo className="w-5 h-5 text-cyan-400" />,
    'Rust': <SiRust className="w-5 h-5 text-orange-400" />,
    'C++': <SiCplusplus className="w-5 h-5 text-blue-400" />,
    'Dart': <SiDart className="w-5 h-5 text-blue-500" />,
    'Flutter': <SiFlutter className="w-5 h-5 text-blue-500" />,
    'Astro': <SiAstro className="w-5 h-5 text-purple-500" />,
    'Kotlin': <SiKotlin className="w-5 h-5 text-purple-600" />,
    'Swift': <SiSwift className="w-5 h-5 text-orange-500" />,
    'C#': <SiSharp className="w-5 h-5 text-purple-500" />,
    'Django': <SiDjango className="w-5 h-5 text-green-600" />,
    'Flask': <SiFlask className="w-5 h-5 text-gray-600" />,
    'FastAPI': <SiFastapi className="w-5 h-5 text-green-500" />,
    'Svelte': <SiSvelte className="w-5 h-5 text-orange-500" />,
    'Nuxt.js': <SiNuxtdotjs className="w-5 h-5 text-green-500" />,
    'Express': <SiExpress className="w-5 h-5 text-gray-600" />,
    'NestJS': <SiNestjs className="w-5 h-5 text-red-500" />,
    'Spring': <SiSpring className="w-5 h-5 text-green-600" />,
    'MongoDB': <SiMongodb className="w-5 h-5 text-green-400" />,
    'PostgreSQL': <SiPostgresql className="w-5 h-5 text-blue-400" />,
    'MySQL': <SiMysql className="w-5 h-5 text-blue-600" />,
    'Firebase': <SiFirebase className="w-5 h-5 text-yellow-500" />,
    'Supabase': <SiSupabase className="w-5 h-5 text-green-500" />,
    'Prisma': <SiPrisma className="w-5 h-5 text-indigo-500" />,
    'Docker': <SiDocker className="w-5 h-5 text-blue-400" />,
    'Kubernetes': <SiKubernetes className="w-5 h-5 text-blue-400" />,
    'GraphQL': <SiGraphql className="w-5 h-5 text-pink-400" />,
    'Redis': <SiRedis className="w-5 h-5 text-red-400" />,
    'Socket.io': <SiSocketdotio className="w-5 h-5 text-gray-600" />,
    'TailwindCSS': <SiTailwindcss className="w-5 h-5 text-teal-400" />,
    'Sass': <SiSass className="w-5 h-5 text-pink-500" />,
    'Bootstrap': <SiBootstrap className="w-5 h-5 text-purple-600" />,
    'MUI': <SiMui className="w-5 h-5 text-blue-500" />,
    'Chakra UI': <SiChakraui className="w-5 h-5 text-teal-500" />,
    'Styled Components': <SiStyledcomponents className="w-5 h-5 text-pink-500" />,
    'Electron': <SiElectron className="w-5 h-5 text-teal-400" />,
    'React Native': <SiReact className="w-5 h-5 text-cyan-500" />,
    'Unity': <SiUnity className="w-5 h-5 text-gray-600" />,
    'Unreal Engine': <SiUnrealengine className="w-5 h-5 text-blue-600" />,
    'Blender': <SiBlender className="w-5 h-5 text-orange-500" />,
    'Webpack': <SiWebpack className="w-5 h-5 text-blue-500" />,
    'Vite': <SiVite className="w-5 h-5 text-purple-500" />,
    'ESLint': <SiEslint className="w-5 h-5 text-purple-600" />,
    'Prettier': <SiPrettier className="w-5 h-5 text-gray-600" />,
    'Jest': <SiJest className="w-5 h-5 text-red-500" />,
    'Cypress': <SiCypress className="w-5 h-5 text-gray-600" />,
    'Storybook': <SiStorybook className="w-5 h-5 text-pink-500" />,
    'Figma': <SiFigma className="w-5 h-5 text-purple-500" />,
    'Adobe': <SiAdobe className="w-5 h-5 text-red-500" />,
    'Linux': <SiLinux className="w-5 h-5 text-yellow-500" />,
    'macOS': <SiMacos className="w-5 h-5 text-gray-600" />,
    'Vim': <SiVim className="w-5 h-5 text-green-500" />,
    'Git': <SiGit className="w-5 h-5 text-orange-500" />,
    'GitHub': <SiGithub className="w-5 h-5 text-gray-600" />,
    'GitLab': <SiGitlab className="w-5 h-5 text-orange-600" />,
    'Bitbucket': <SiBitbucket className="w-5 h-5 text-blue-600" />,
    'Vercel': <SiVercel className="w-5 h-5 text-white" />,
    'Netlify': <SiNetlify className="w-5 h-5 text-teal-500" />,
    'Heroku': <SiHeroku className="w-5 h-5 text-purple-600" />,
    'DigitalOcean': <SiDigitalocean className="w-5 h-5 text-blue-500" />,
    'AWS S3': <SiAmazons3 className="w-5 h-5 text-orange-500" />,
    'AWS': <SiAmazon className="w-5 h-5 text-orange-500" />,
    'Google Cloud': <SiGooglecloud className="w-5 h-5 text-blue-500" />,
    'TensorFlow': <SiTensorflow className="w-5 h-5 text-orange-500" />,
    'PyTorch': <SiPytorch className="w-5 h-5 text-red-500" />,
    'OpenCV': <SiOpencv className="w-5 h-5 text-green-500" />,
    'NumPy': <SiNumpy className="w-5 h-5 text-blue-500" />,
    'Pandas': <SiPandas className="w-5 h-5 text-purple-500" />,
    'SciPy': <SiScipy className="w-5 h-5 text-blue-600" />,
    'Jupyter': <SiJupyter className="w-5 h-5 text-orange-500" />,
    'Anaconda': <SiAnaconda className="w-5 h-5 text-green-500" />,
    'R': <SiR className="w-5 h-5 text-blue-500" />,
    'Solidity': <SiSolidity className="w-5 h-5 text-gray-600" />,
    'Web3.js': <SiWeb3Dotjs className="w-5 h-5 text-orange-500" />,
    'Ethereum': <SiEthereum className="w-5 h-5 text-blue-600" />,
  };

  return iconMap[language] || <FaCode className="w-5 h-5 text-gray-400" />;
}; 